name: create invite label
on: push

jobs:
  create-invite-label:
    runs-on: ubuntu-latest
    steps:
      - name: create invite label
        uses: actions-cool/issues-helper@v3
        continue-on-error: true
        with:
          actions: 'create-label'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          label-name: 'invite'